# this docker-compose file is for the local development environment
version: '3.9'

services:
  app:
    build:
      context: .
    command: >
      sh -c "python manage.py makemigrations &&
      python manage.py wait_for_db && 
      python manage.py migrate && 
      python manage.py runserver 0.0.0.0:8000"
    ports: 
      - 8000:8000
    volumes:
      - ./app:/app
      # below maps the contents of the vol folder back to our dev folder
      - ./vol:/vol
    environment:
      - SECRET_KEY=myownsecretKee
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=dockdb
      - DB_USER=devuser
      - DB_PASS=changeme
    depends_on:
      - db
      
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=dockdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme